### ISSUE TITLE
Request: New Release

### ISSUE THREAD

**Issue by Nebukadneza** [denisenkom/pytds#122]
Hi,

thanks for this great project! Given the recent fix of #115 which is a quite critical "short read" bug, I think that many users would profit from the severely increased correctness and reliability this brings.

Would that warrant a new release soon?

Thanks! ^_^

**Comment by denisenkom** [comment]
released: https://pypi.org/project/python-tds/1.11.0/

**Comment by Nebukadneza** [comment]
Thank you! This helps us a lot …
