### ISSUE TITLE
SSPI not working in linux due to WINFUNTYPE import

### ISSUE THREAD

**Issue by sam2332** [denisenkom/pytds#140]
https://github.com/denisenkom/pytds/blob/7c73812444dd3c38c893dd88d14e138908069bd0/src/pytds/sspi.py#L2

This line is giving errors on linux systems due to usage of winctypes, is there anyway to migrate to a flow that does not use the windows only types?

**Comment by takoau** [comment]
@sam2332 can you upload the error?

**Comment by takoau** [comment]
@sam2332 Why not use Kerberos as you login from Linux?
[Active Directory authentication for SQL Server on Linux](https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-active-directory-auth-overview?view=sql-server-ver16)

**Comment by denisenkom** [comment]
SSPI is only available on Windows.  On Linux you need to use Kerberos or NTLM.
