### ISSUE TITLE
DistributionNotFound error when using python-tds on AWS Lambda

### ISSUE THREAD

**Issue by paldana** [denisenkom/pytds#146]
Hi, I'm trying to use pytds on a lambda function to connect to an MS SQL database. Everything works fine when I run the code locally on a MacOS computer. However, when I try to test it on the actual Lambda function on AWS Console, I'm getting the "DistributionNotFound" error. Below is the complete log

> {
>   "errorMessage": "The 'python-tds' distribution was not found and is required by the application",
>   "errorType": "DistributionNotFound",
>   "requestId": "",
>   "stackTrace": [
>     "  File \"/var/lang/lib/python3.9/importlib/__init__.py\", line 127, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n",
>     "  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n",
>     "  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
>     "  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
>     "  File \"<frozen importlib._bootstrap>\", line 680, in _load_unlocked\n",
>     "  File \"<frozen importlib._bootstrap_external>\", line 850, in exec_module\n",
>     "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
>     "  File \"/var/task/lambda_function.py\", line 5, in <module>\n    from test_mssql import connect_mssql\n",
>     "  File \"/var/task/test_mssql.py\", line 4, in <module>\n    import pytds\n",
>     "  File \"/var/task/pytds/__init__.py\", line 46, in <module>\n    __version__ = pkg_resources.get_distribution('python-tds').version\n",
>     "  File \"/var/lang/lib/python3.9/site-packages/pkg_resources/__init__.py\", line 466, in get_distribution\n    dist = get_provider(dist)\n",
>     "  File \"/var/lang/lib/python3.9/site-packages/pkg_resources/__init__.py\", line 342, in get_provider\n    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]\n",
>     "  File \"/var/lang/lib/python3.9/site-packages/pkg_resources/__init__.py\", line 886, in require\n    needed = self.resolve(parse_requirements(requirements))\n",
>     "  File \"/var/lang/lib/python3.9/site-packages/pkg_resources/__init__.py\", line 772, in resolve\n    raise DistributionNotFound(req, requirers)\n"
>   ]
> }

How should I resolve this issue?

Thanks,

Paul

**Comment by takoau** [comment]
Hi Paul,

Lambda does not support a proper module installation hence package manager and python-tds needs it.  Not much can be done unless hacking the source.

Run the following on your Mac:
>>> import pkg_resources
>>> pkg_resources.get_distribution('python-tds').version
'1.11.0'

Hardcode line 45 of __init__.py with this value.

Regards,
Tako

**Comment by paldana** [comment]
Hi Tako,

Thanks for your response! Hardcoding the version number worked. Hopefully there will be a better way to do this in the future. 

For future reference, I had to download the source code and include pytds directory with the lambda handler function to make it work.

Thanks again!

Best, 

Paul
