### ISSUE TITLE
Support table-value parameters?

### ISSUE THREAD

**Issue by mburbea** [denisenkom/pytds#15]
Is there any plan to support table-valued parameters?
Currently, I have an process that reads and builds a dataset and then serializes it and stores one row of data at a time in a loop. This was fine when the amount of data was small, but now that I have moved to production I process about 10,000 records the chattiness and the performance of the execution is becoming too slow for a good real time feedback.

**Comment by denisenkom** [comment]
Added support for TVPs: https://python-tds.readthedocs.io/en/latest/#table-valued-parameters
