### ISSUE TITLE
Migrate ntlm-auth to pyspnego

### ISSUE THREAD

**Issue by mariusdkm** [denisenkom/pytds#156]
I think this library should be migrated to [pyspnego](https://github.com/jborean93/pyspnego) and away from [ntlm-auth](https://github.com/jborean93/ntlm-auth) because ntlm-auth doesn't get any more updates and the readme states that one should switch.
NTLM requests also migrated this year https://github.com/requests/requests-ntlm/pull/126.

**Comment by mariusdkm** [comment]
This is partly because ntlm-auth uses the hashlib md4 hashing algorithm, which is no longer available in newer versions. pyspnego uses its own implementation.
I would be open to making a PR to fix this issue if that is wished for.

**Comment by denisenkom** [comment]
This is already done, take a look: https://github.com/denisenkom/pytds/issues/154

**Comment by mariusdkm** [comment]
Ah, alright, thanks.
