### ISSUE TITLE
Issue with python 3.12

### ISSUE THREAD

**Issue by EliaBracciSumo** [denisenkom/pytds#159]
While trying to import pytds library using python 3.12 I got the following issue:
```
File "/var/lang/lib/python3.12/site-packages/pytds/__init__.py", line 69, in <module>
  import pkg_resources  # type: ignore # fix later
  ^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by denisenkom** [comment]
This issue is already fixed in https://github.com/denisenkom/pytds/pull/157.  Awaiting next release.

**Comment by EliaBracciSumo** [comment]
@denisenkom thank you very much! Is there any plan for the next release?

**Comment by jackwotherspoon** [comment]
+1 Kindly waiting on next version release 😄

**Comment by denisenkom** [comment]
New version 1.15.0 was released
