### ISSUE TITLE
percent-sign escaping in SQL text messes with SQLAlchemy literal binds

### ISSUE THREAD

**Issue by gordthompson** [denisenkom/pytds#171]
I have been trying to get SQLAlchemy 2.0's test suite to pass with [sqlalchemy-pytds](https://pypi.org/project/sqlalchemy-pytds/) and have hit upon a bit of a quagmire. The test suite includes a number of tests for percent-sign escaping with drivers that use the "pyformat" paramstyle. Those drivers include [mysqlclient](https://pypi.org/project/mysqlclient/) and [PyMySQL](https://pypi.org/project/PyMySQL/) for MySQL, along with [psycopg2](https://pypi.org/project/psycopg2/) and [psycopg](https://pypi.org/project/psycopg/) for PostgreSQL. (pymssql also uses pyformat, but it is a [special case](https://github.com/sqlalchemy/sqlalchemy/blob/7949426428f1ec19381116e025b95f86417a85fc/lib/sqlalchemy/dialects/mssql/pymssql.py#L45-L46).)

My difficulty is that pytds handles double-percents differently from the aforementioned drivers when a parameter-less query is executed and an empty dict or tuple is passed for the parameters. SQLAlchemy is quite consistent in its behaviour, e.g.,

```python
engine.echo = True
with engine.begin() as conn:
    conn.execute(sa.text("SELECT 1 AS foo"))
"""
2024-09-05 15:27:29,887 INFO sqlalchemy.engine.Engine SELECT 1 AS foo
2024-09-05 15:27:29,888 INFO sqlalchemy.engine.Engine [generated in 0.00076s] {}
"""
```

Notice the empty dict `{}`. All of the other drivers use that empty dict/tuple as their cue to "un-escape" double-percents, but pytds does not:

```python
import sqlalchemy as sa

test_cases = [
    ("mysqlclient", "mysql+mysqldb://scott:tiger@localhost:3307/test"),
    ("pymysql", "mysql+pymysql://scott:tiger@localhost:3307/test"),
    ("psycopg2", "postgresql://scott:tiger@192.168.0.199/test"),
    ("psycopg", "postgresql+psycopg://scott:tiger@192.168.0.199/test"),
    ("pytds", "mssql+pytds://scott:tiger^5HHH@192.168.0.199/test"),
]

for case, connection_string in test_cases:
    print(f"[{case}]")
    engine = sa.create_engine(connection_string)
    crsr = engine.raw_connection().dbapi_connection.cursor()
    crsr.execute("SELECT 'x %% y' AS foo")
    print(f"  no params: {crsr.fetchone()}")
    crsr.execute("SELECT 'x %% y' AS foo", {})
    print(f"  empty dict: {crsr.fetchone()}")
    crsr.execute("SELECT 'x %% y' AS foo", tuple())
    print(f"  empty tuple: {crsr.fetchone()}")
"""
[mysqlclient]
  no params: ('x %% y',)
  empty dict: ('x % y',)
  empty tuple: ('x % y',)
[pymysql]
  no params: ('x %% y',)
  empty dict: ('x % y',)
  empty tuple: ('x % y',)
[psycopg2]
  no params: ('x %% y',)
  empty dict: ('x % y',)
  empty tuple: ('x % y',)
[psycopg]
  no params: ('x %% y',)
  empty dict: ('x % y',)
  empty tuple: ('x % y',)
[pytds]
  no params: ('x %% y',)
  empty dict: ('x %% y',)
  empty tuple: ('x %% y',)
"""
```

That significantly complicates literal binds because "to double or not to double" percent signs depends on whether the query *actually uses* parameters, and literal binding often takes place outside of the context where it is feasible (or even possible) to determine whether or not the query has "real" parameters.

In my ideal world, pytds would behave like the other drivers. I understand that an arbitrary change to pytds might carry too big a risk of breaking existing code, but an opt-in change (e.g., via a parameter at connection time) would make sqlalchemy-pytds a whole lot easier to support.

Thanks for listening. Comments welcome.

( cc: @m32 )

**Comment by m32** [comment]
sqlite return the same result as pytds
always use sa.text(raw_sql) when using raw commands in sqlalchemy because they are parsed and adjusted to the driver, in this case:
```
    engine = sa.create_engine(connection_string)
    with engine.begin() as conn:
        #crsr = engine.raw_connection().dbapi_connection.cursor()
        stmt = sa.text("SELECT 'x %% y' AS foo")
        c = conn.execute(stmt)
        print(f"  no params: {c.fetchone()}")
        c = conn.execute(stmt, {})
        print(f"  empty dict: {c.fetchone()}")
        c = conn.execute(stmt, tuple())
        print(f"  empty tuple: {c.fetchone()}")

```

**Comment by gordthompson** [comment]
> sqlite return the same result as pytds 

sqlite uses "qmark", not "pyformat", so escaping of percent signs does not apply

```python
print(engine.dialect.name)  # sqlite
print(engine.dialect.paramstyle)  # qmark
```

> always use sa.text(raw_sql) when using raw commands in sqlalchemy because they are parsed and adjusted to the driver

The issue is the same:

```python
import sqlalchemy as sa

test_cases = [
    ("mysqlclient", "mysql+mysqldb://scott:tiger@localhost:3307/test"),
    ("pymysql", "mysql+pymysql://scott:tiger@localhost:3307/test"),
    ("psycopg2", "postgresql://scott:tiger@192.168.0.199/test"),
    ("psycopg", "postgresql+psycopg://scott:tiger@192.168.0.199/test"),
    ("pytds", "mssql+pytds://scott:tiger^5HHH@192.168.0.199/test"),
]

for case, connection_string in test_cases:
    print(f"[{case}]")
    engine = sa.create_engine(connection_string)
    with engine.begin() as conn:
        result = conn.scalar(sa.text("SELECT 'x % y' AS foo"))
        print(f"  {result}")
"""
[mysqlclient]
  x % y
[pymysql]
  x % y
[psycopg2]
  x % y
[psycopg]
  x % y
[pytds]
  x %% y
"""
```

**Comment by m32** [comment]
During the query compilation by sqlachemy, it is converted according to the type of parameters, in pyformat the '%' character must changed to '%%' regardless of whether the parameters are present or not in the call method (cursor.execute).

Pytds performs its own query conversion (operation%parameters) and then the %% character is changed back to %.
However, it does not do this in the absence of parameters and therefore an inconsistency occurs see in tds_session.py:915

change default_paramstyle = 'pyformat' to default_paramstyle = 'named' in sqlalchemy_pytds/connector.py
```
    with engine.begin() as conn:
        #crsr = engine.raw_connection().dbapi_connection.cursor()
        for sstmt in (
            "SELECT 'x % y' + :n AS foo",
            "SELECT 'x % y' AS foo",
        ):
            stmt = sa.text(sstmt)
            print(f"  stmt: {sstmt}")
            print(f"  compiled: {stmt}")
            result = conn.scalar(stmt, ({'n': 'a'}))
            print(f"  result: {result}")
```

[pytds]
  stmt: SELECT 'x % y' + :n AS foo
  compiled: SELECT 'x % y' + :n AS foo
do_execute( SELECT 'x %% y' + %(n)s AS foo , {'n': 'a'} )
  result: x % ya
  stmt: SELECT 'x % y' AS foo
  compiled: SELECT 'x % y' AS foo
do_execute( SELECT 'x %% y' AS foo , {} )
  result: x %% y

**Comment by gordthompson** [comment]
FWIW, this change produces the results I would like to see

```patch
Index: src/pytds/tds_session.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/pytds/tds_session.py b/src/pytds/tds_session.py
--- a/src/pytds/tds_session.py	(revision c186decfcc141a1a51786a8a9a9e8277db2c12c3)
+++ b/src/pytds/tds_session.py	(date 1725639987172)
@@ -865,7 +865,7 @@
         params: list[Any] | tuple[Any, ...] | dict[str, Any] | None = None,
     ) -> None:
         self._ensure_transaction()
-        if params:
+        if params is not None:
             named_params = {}
             if isinstance(params, (list, tuple)):
                 names = []
```

Test code

```python
import pytds
with pytds.connect('192.168.0.199', 'test', 'scott', 'tiger^5HHH') as conn:
    cases = [
        ("no params", None),
        ("empty tuple", tuple()),
        ("empty dict", {})
    ]
    for case, param in cases:
        print(f"[{case}]")
        with conn.cursor() as cur:
            cur.execute("SELECT 'x %% y' AS foo", param)
            rtn = cur.fetchone()[0]
            print(f"  {rtn}")
```

Before change

```
[no params]
  x %% y
[empty tuple]
  x %% y
[empty dict]
  x %% y
```

After change

```
[no params]
  x %% y
[empty tuple]
  x % y
[empty dict]
  x % y
```

**Comment by m32** [comment]
please make PR to this repo
