### ISSUE TITLE
support for python versions up to and including 3.13

### ISSUE THREAD

**Issue by mjk4** [denisenkom/pytds#173]
Please upgrade this package to support newer python versions.
In setup.py I only see up to python 3.5
TIA

**Comment by denisenkom** [comment]
Created pull request https://github.com/denisenkom/pytds/pull/174, please take a look and approve

**Comment by mjk4** [comment]
Thanks for the quick reply!  I'll try to review it in the next few days unless someone reviews and approves it first.

**Comment by gordthompson** [comment]
#174 has been merged

**Comment by mjk4** [comment]
Thanks again!  Do you know if you'll have a release soon for these new Python versions?

**Comment by denisenkom** [comment]
Yes, planning to release soon. Created https://github.com/denisenkom/pytds/pull/175 for preparation for release, please approve.

**Comment by denisenkom** [comment]
Version 1.16.0 is now available on pypi
