### ISSUE TITLE
Support SSL

### ISSUE THREAD

**Issue by jordanorc** [denisenkom/pytds#25]
When I try to connect to Windows Azure SQL, it raises the following exception:

```
AttributeError: '_TdsSession' object has no attribute '_sock'
```

Changing line 3199 on file tds.py from:

```
self._sock = ssl.wrap_socket(self._sock, ssl_version=ssl.PROTOCOL_SSLv3)
```

to:

```
self._sock = ssl.wrap_socket(self._transport._sock, ssl_version=ssl.PROTOCOL_SSLv3)
```

Solves the issue. But then I get the following error:

```
ssl.SSLError: [Errno 8] _ssl.c:507: EOF occurred in violation of protocol
```

Has anyone had success when connecting to Azure using pytds?

**Comment by denisenkom** [comment]
Additional options to consider:
https://gitlab.com/m2crypto/m2crypto
https://github.com/trevp/tlslite

**Comment by denisenkom** [comment]
and that:
https://pypi.python.org/pypi/pyOpenSSL

**Comment by gfranxman** [comment]
bump.     I'm not a windows user, but I'd really like to use this to help migrate a node app to python which uses a pure javascript implementation that is capable of even active directory authentication.
Their code looks like
var sql = require('mssql'); 
var cfg = {
  domain: process.env.ADDOMAIN,
  user: process.env.ADUSER,
  password: process.env.ADPASSWD,
  server: dbhost,
  database: dbname,
  encrypt: true
};
sql.connect( cfg ).then( ...

Wouldn't that be nice? Maybe I'll get time to attempt to reverse how they did it.

**Comment by cristianocoelho** [comment]
Any ideas on how to work with this? Azure forces you to use SSL and doing code changes to use SSL doesn't seem to work in any way.

**Comment by lnattrass** [comment]
It looks like you might be able to do this using Memory BIO in python 3.5+

I needed to print out the certificate from an SQL server, so ended up writing this digusting piece of code: 
https://gist.github.com/lnattrass/a4a91dbf439fc1719d69f7865c1b1791

Works for us though..

**Comment by denisenkom** [comment]
Initial implementation is available in tls-support branch.  Please take a look. Suggestions welcome!

**Comment by denisenkom** [comment]
Released version 1.9.0 with TLS support

**Comment by ahmedpopal456** [comment]
Hello :); I had a quick question; was trying to connect to a Microsoft SQL Server on Azure using the newest version of pytds, which supports TLS; I was wondering if there was a way to enable encryption on the client side (Error: Client does not have encryption enabled but it is required by server, enable encryption and try connecting again)

**Comment by denisenkom** [comment]
you need to specify cafile parameter for connect function: https://python-tds.readthedocs.io/en/latest/pytds.html#pytds.connect

**Comment by eydelrivero** [comment]
Documentation says `cafile` is the 

> Name of the file containing trusted CAs in PEM format, if provided will enable TLS

, but where can I get that file name from? Do I need to download a certificate? Can you elaborate with an example? I'm trying to use pytds to connect to an Azure SQL database.

**Comment by denisenkom** [comment]
I think there should be a download link somewhere at Azure control panel.  First place I would check is connection string suggested by Azure, it might have a link to the root certificate.

**Comment by ahmedpopal456** [comment]
Yes, I did find the link to the certificate ! Now, I guess copying the file to the VM and pointing the path to the cafile attribute should be enough?

**Comment by AnilChandore** [comment]
@ahmedpopal456 did it work? If yes then, can you please share how did you download the pem file and what it contained?

**Comment by sudo-shubham** [comment]
@ahmedpopal456 Can you share how did you get the cafile?

**Comment by dmlundeby** [comment]
I see this thread is old, but I also had troubles specifying the `cafile`. However, I found the following solution to work for me:

I'm trying to access a MSSQL DB in Azure. It turns out its certificate is trusted by Mozilla. Thus, I could use the `certifi` package, and use `certifi.where()` as `cafile`. I also needed to set `validate_host` to `False`.

**Comment by sfc-gh-mrojas** [comment]
Thanks @dmlundeby this really unblocked me I am able to  connect with:

```
import certifi
with pytds.connect('xxxx.database.windows.net', 'database', 'user', 'password',cafile=certifi.where(),validate_host=False) as conn:
        with conn.cursor() as cur:
            cur.execute("select 1")
            cur.fetchall()
            cur.execute("insert into mytest_table(col1,col2) values('hola', 3200)")
            cur.execute("commit")
            return "done"
```

**Comment by denisenkom** [comment]
You should not set `validate_host` to false since that option makes you vulnerable to MitM attack.  You should set it to true.
