### ISSUE TITLE
does not support DSN

### ISSUE THREAD

**Issue by sp1d3rx** [denisenkom/pytds#33]
Needs to support DSN syntax. Otherwise it's not dbapi 2.0 compliant.

I would suggest you use dsnparse as that will make it easy.

**Comment by denisenkom** [comment]
Actually it is compliant: http://legacy.python.org/dev/peps/pep-0249/#connect
```
connect( parameters... )
Constructor for creating a connection to the database.

Returns a Connection Object. It takes a number of parameters which are database dependent.
```

**Comment by sp1d3rx** [comment]
Look at footnote 1. Only thing not optional is dsn.

**Comment by denisenkom** [comment]
Implemented
