### ISSUE TITLE
AppEngine support

### ISSUE THREAD

**Issue by kenttregenza** [denisenkom/pytds#42]
Great library.... would be even better to have this official support/work the Google AppEngine environment.

I have already made changes to get it going but not sure how to submit a pull request for you. Basically you need to modify the tds.py to 
1. USE_CORK = False (AppEngine doesn't support TCP_CORK)
2. Convert bytearray to str for _sock.sendall in _write method  (AppEngine doesn't support bytearray)

**Comment by denisenkom** [comment]
Why can't you create a pull request?

**Comment by kenttregenza** [comment]
Sorry for delay... been a while off on other work. I'll fork the project and do a pull request if you still would like one.

**Comment by denisenkom** [comment]
I will close this one, if you still need this, you can create a pull request.
