### ISSUE TITLE
Would really like a new release of pytds!

### ISSUE THREAD

**Issue by joshuahlang** [denisenkom/pytds#51]
EDIT: It seems I was mistaken, and passing a NULL VARBINARY is supported in the current released version of pytds. It just isn't documented in that version. Even still, a new release of pytds would be appreciated!

The latest version of pytds on pypi is great, but doesn't support passing NULL for VARBINARY parameters. The new version seems to (see below). Would it be possible to get a release to pypi of the latest code?

    # Must explicitly indicate the column is binary in order to pass NULL for VARBINARY
    pytds.Column(type=pytds.VarBinaryMax())

Is there a better/cleaner way to achieve this?

Note that not passing something like this for a *VARBINARY* parameter will result in the following error:

    pytds.tds.OperationalError: Implicit conversion from data type nvarchar to varbinary is not allowed. Use the CONVERT function to run this query.

**Comment by denisenkom** [comment]
Released as version 1.8.0
