### ISSUE TITLE
Circular reference between Connection and Cursor

### ISSUE THREAD

**Issue by peterdemin** [denisenkom/pytds#55]
Each cursor stores reference to it's connection. And each connection stores reference to active (Connection._active_cursor) cursor. Both classes define __del__ method. This makes them noncollectable objects (https://docs.python.org/2/library/gc.html#gc.garbage). Which leads to memory leak.

**Comment by denisenkom** [comment]
Looks like cursor and connection objects don't need __del__ methods at all, I removed those methods.

**Comment by peterdemin** [comment]
Thank you! Could please make a pypi release?

**Comment by denisenkom** [comment]
Can you confirm that this is fixing your issue?  I could not verify the fix.

**Comment by peterdemin** [comment]
I confirm. There is no more memory leaks with this patch.

**Comment by denisenkom** [comment]
released 1.8.2
