### ISSUE TITLE
Doesn't support AlwaysOn

### ISSUE THREAD

**Issue by nullv01d** [denisenkom/pytds#56]
pytds does not support AlwaysOn for high availability ms sql servers.
It would be a great help if the same can be added.

Thank you.

**Comment by denisenkom** [comment]
pytds currently support HA by using failover_partner parameter: http://python-tds.readthedocs.org/en/latest/pytds.html#pytds.connect

If you specify this parameter pytds will seamlessly switch to failover partner database if primary is not available.

This works well if you have two MSSQL servers in mirroring configuration.

I am not aware about AlwaysOn configuration, how does it work?  How do you configure, say ADODB driver to use AlwaysOn?

**Comment by nullv01d** [comment]
The problem with Database Mirroring is we can't mention multiple secondary (failover partner) servers. Also, multiple databases can't be mirrored at the same time. That's where AlwaysOn helps.

And I'm not entirely sure but since ADODB supprts DSN, adding `MultiSubnetFailover=True` *should* do the trick! Because `MultiSubnetFailover` is what someone has to add to the connection string to use AlwaysOn.

**Comment by denisenkom** [comment]
It is now added in commit: https://github.com/denisenkom/pytds/commit/7c9b73ea101b1cdcb7a48a7514f6cd76afe3942b
