### ISSUE TITLE
fetchall() after UPDATE operation throws pytds.tds.Error

### ISSUE THREAD

**Issue by nullv01d** [denisenkom/pytds#57]
Hello,

When we call `cursor.fetchall()` after `cursor.execute()` an UPDATE operation, *pytds* throws an exception of type `pytds.tds.Error`.
Shouldn't it throw `pytds.OperationalError`? Because such cases fall under *Operational Errors*?

Thank you.

**Comment by denisenkom** [comment]
I think it should instead be ProgrammingError:
Exception raised for programming errors, e.g. table not found or already exists, syntax error in the SQL statement, wrong number of parameters specified, etc. It must be a subclass of DatabaseError

OperationalError means: Exception raised for errors that are related to the database's operation and **not necessarily under the control of the programmer**, e.g. an unexpected disconnect occurs, the data source name is not found, a transaction could not be processed, a memory allocation error occurred during processing, etc. It must be a subclass of DatabaseError .

In this particular case programmer has control over which method he calls.

**Comment by nullv01d** [comment]
Makes sense. :+1:  So will you be making it throw ProgrammingError in future versions of pytds?

BTW, `pymssql` throws OperationalError for such cases. Don't know what their explanation is. :)
