### ISSUE TITLE
cursor._session is None when iterating over cursor directly

### ISSUE THREAD

**Issue by jmartinez-jobsity** [denisenkom/pytds#59]
When running something like:

``` python
with pytds.connect(as_dict=True, **settings.mssql) as conn:
    with conn.cursor() as cursor:
        cursor.callproc(self.SP_NAME)
        for row in cursor:
            print(row)
```

I'm getting a `'NoneType' object has no attribute 'fetchone'` from the `_session` being None

``` python
> /usr/lib/python3.5/site-packages/pytds/__init__.py(744)fetchone()
-> row = self._session.fetchone()
(Pdb) self._session is None
True
```

For now, the workaround is to iterate over `cursor.fetchall()`, but I think iterating over the cursor directly should not raise that exception

**Comment by denisenkom** [comment]
Can you provide full stack trace?  Also can you test it on current tip of master branch?

**Comment by jmartinez-jobsity** [comment]
Seems to be fixed now
