### ISSUE TITLE
Add support for sending parameters as varchar (either via switch or type based)

### ISSUE THREAD

**Issue by mburbea** [denisenkom/pytds#6]
The `make_param` method never will make a parameters type varchar.
This is problematic as if you are using a query that seeks against an indexed varchar column, sql server will opt to convert the column to nvarchar rather than converting the parameter to varchar.
e.g.

``` sql
select *
from my_table
where name = @name --name is a varchar(50)
```

Should use the index on name, but will not. I will have to explicitly convert the parameter to varchar. 

I propose that if the type of the parameter sent in is `str` use `varchar`, `varchar(max)` or `text`. And if the type is `unicode` use `nvarchar`, `nvarchar(max)` or `ntext` 

Finally, MS-SQL default type is `int` not `nvarchar`. If I pass `None` as a parameter it should be encoded as an int. This is minor point. 
proof::

``` sql
select null [a] into __t
select column_name,data_type from information_schema.columns where table_name='__t'
```

**Comment by yesdeepakverma** [comment]
I also stuck with the same problem when using MS-SQL -2008 with pytds (using django-sqlserver).
What I ended up using is defining a setting variable in Django setting file say DB_CHAR_FIELD = "varchar"
and then patching django-sqlserver -> sqlserver_ado->base.py with following code.
from django.conf import settings
CHAR_FIELD = getattr(settings, 'DB_CHAR_FIELD', 'nvarchar')
and then-> Old code
        'CharField':                    'nvarchar(%(max_length)s)',
        'CommaSeparatedIntegerField':   'nvarchar(%(max_length)s)',
New Code:->
        'CharField':                    CHAR_FIELD+'(%(max_length)s)',
        'CommaSeparatedIntegerField':   CHAR_FIELD+'(%(max_length)s)',
 

I might be sending this patch to django-sqlserver
