### ISSUE TITLE
OUTPUT clause returns wrong result set

### ISSUE THREAD

**Issue by wstucco** [denisenkom/pytds#63]
when running an `execmany` query that uses the `OUTPUT` clause, only one result is returned.  
Example:   

```python
pytds.connect(**config)
connection.autocommit = True

# test table has only one field name varchar(20)
cursor = connection.cursor()
query = "INSERT INTO [test] (name) OUTPUT inserted.name values (%s)"
cursor.executemany(query, [("mike"), ("john"), ("robert")])

cursor.fetchall() # returns only one element, should return 3 of them

```

**Comment by denisenkom** [comment]
executemany should not be used with queries which produce result sets.  According to spec this results in undefined behavior: https://www.python.org/dev/peps/pep-0249/#executemany
