### ISSUE TITLE
getaddrinfo port parameter type on sock open

### ISSUE THREAD

**Issue by chetmancini** [denisenkom/pytds#64]
Hi, I'm running Django 1.8.7 on Ubuntu, using the master branch of `django-sqlserver` to connect to a remote SQLServer via pytds.

I was using the released 1.8.2, and ran across an issue. I tried copying the master branch and using it directly and I get the same issue.

```
Cannot connect to server '<my-sql-server>: getaddrinfo() argument 2 must be integer or string", error('getaddrinfo() argument 2 must be integer or string',)
```

I put a print on `(host, port)` on line 282 and both the parameters were there. Guessing there was an issue with the port I put a cast to `int` in and lo and behold it works fine.
```
sock = socket.create_connection((host, int(port)), retry_time)
```

I'm not entirely clear in my mind *why* that's the case and no one else has run into it as far as I've seen. I'd be happy to make a pull request if you have an idea why this might bubble up now and if it'd be safe for all users of the package.

Thanks!

**Comment by DariuszOstolski** [comment]
I wouldn't do, according to documentation it can be a string an integer or None. In your case it seems that this was something different. Could you please provide a connection string that you were using when this error happened?

**Comment by chetmancini** [comment]
@DariuszOstolski ah it's a `str`/`unicode` bug. I casted to `str()` and it worked too. 
I'm using python 2.7.13. `django-sqlserver` has `from __future__ import unicode_literals` turned on. 

My host param is coming as a `str` but the port has a get with default `u'1433'` in the wrapper which gets passed directly into `pytds.connect(` on line `1019`, and it seems `getaddrinfo` does not support unicode string ports.

I guess I could resolve by manually forcing the port as an integer or someday upgrading my legacy codebase to Python3. :)
