### ISSUE TITLE
Add support for TDS 5, Sybase, maybe

### ISSUE THREAD

**Issue by javjuarez** [denisenkom/pytds#69]
I am having a problem by trying to connect to a database url and port, maybe I'm making it wrong, I try the follow

`with pytds.connect('132.248.205.170:4101', 'act_firma_tit', '#mypassword') as conn:`

and I got this error

`pytds.tds.LoginError: ("Cannot connect to server '132.248.205.170:4101': [Errno 11001] getaddrinfo failed", gaierror(11001, 'getaddrinfo failed'))`

How can I connect correctly?

**Comment by javjuarez** [comment]
I made it wrong hehe, now I made this

`with pytds.connect(dsn='132.248.205.170', user='act_firma_tit', password='', port=4101, login_timeout=30) as conn:`

and I got this error

`Empty packet doesn make any sense`

**Comment by denisenkom** [comment]
Looks like the thing you are connecting to does not understand TDS protocol.

**Comment by knedlsepp** [comment]
I'm having the same problem. In my case the explanation seems to be: "pytds does not currently support TDS version 5.0".

**Comment by denisenkom** [comment]
What version of SQL server do you have?

**Comment by knedlsepp** [comment]
It's a "SAP ASE version 16.0 SP02 PL06"

**Comment by denisenkom** [comment]
this driver works only with MS SQL Server, it is not compatible with Sybase

**Comment by knedlsepp** [comment]
While I get that the version 5.0 of TDS is unsupported, I think it is not unreasonable to assume that pytds *could* support Sybase, as this is basically only the legacy version of MS SQL Server. So I'd like to leave this as a feature request. (Knowing that this request might not be fulfilled in the foreseeable future.)

**Comment by denisenkom** [comment]
I believe Sybase TDS is too different at this point from MSSQL TDS.  I think Sybase should be supported by separate driver.
