### ISSUE TITLE
readonly parameter of connect() doesn't seem to work correctly

### ISSUE THREAD

**Issue by the-hof** [denisenkom/pytds#78]
I would expect this to set the applicationintent parameter in the connection string, but I'm not sure how to see the actual connection string and I get this error:

pytds.tds.OperationalError: The target database ('DATABASE') is in an availability group and is currently accessible for connections when the application intent is set to read only. 

Is there something else that needs to be done?

**Comment by denisenkom** [comment]
readonly flag is passed here: https://github.com/denisenkom/pytds/blob/3b9bac7dfaab1070c5202acd912ab8154849d0a7/pytds/tds.py#L1420

You can use Wireshark to verify whether this flag is set correctly.
